[package]
name = "tablify"
version = "0.1.0"
authors = ["Yuki Suzuki <y-suzuki@radiol.med.osaka-u.ac.jp>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
clap = "2"
csv = "1"
serde = { version = "1", features = ["derive"] }
encoding_rs = "0"
calamine = "0"
wasm-bindgen = "0.2"

[dependencies.tera]
version = "1"
default-features = false

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
