name: Deploy to Github Pages

on:
  push:
    tags:
      - 'v*'
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install wasm-pack
      run: cargo install wasm-pack
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Build
      working-directory: ./www
      run: npm run build-wasm && npm install && npm run build
    - name: Publish
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./www/dist
