name: Deploy to Github Pages

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Modify Cargo.toml
      run: sed -i "s/simple_excel_writer/#simple_excel_writer/" Cargo.toml
    - name: Install wasm-pack
      run: cargo install wasm-pack
    - name: Run wasm-pack
      run: wasm-pack build
      
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: cd ./www && yarn
    - name: Build react
      run: cd ./www && yarn build
    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./www/build
